# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 555208b36d9885b5a9f30c6e82707aa3340f6e52254ba121a0dd7aefe0fd229885e0c7e8d9bda10f94674711fdc8c2159fd8dc5698b297f320df931b2817d189

test:
  secret_key_base: e489263f68d1a7448b62e5ca0fa43837c56b1d4d888ff15e06276ced089ff3036449099266230c1a535b90430a1b810c3e37b701da2a3d930a6ed025724424c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
